// generated by gemini
#ifndef RINGBUF_H
#define RINGBUF_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

struct ringbuf_t {
    uint8_t *buffer;
    int capacity;
    int head;
    int tail;
};

typedef struct ringbuf_t ringbuf_t;

void ringbuf_init(ringbuf_t *rb, void *buffer, int capacity);

int ringbuf_capacity(const ringbuf_t *rb);
int ringbuf_bytes_free(const ringbuf_t *rb);
int ringbuf_bytes_used(const ringbuf_t *rb);

int ringbuf_is_full(const ringbuf_t *rb);
int ringbuf_is_empty(const ringbuf_t *rb);

int ringbuf_push(ringbuf_t * restrict rb, const void * restrict src, int count);
int ringbuf_pop(ringbuf_t * restrict rb, void * restrict dst, int count);
int ringbuf_peek(const ringbuf_t * restrict rb, void * restrict dst, int count);

const void *ringbuf_tail(const ringbuf_t *rb);
const void *ringbuf_head(const ringbuf_t *rb);

#ifdef __cplusplus
}
#endif

#endif // RINGBUF_H